### ISSUE TITLE
关于低版本升级后出错

### ISSUE THREAD

**Issue by Tobess** [overtrue/laravel-pinyin#11]
![123](https://cloud.githubusercontent.com/assets/12328610/20882517/51b66b7c-bb1c-11e6-88ac-88b56cbb8911.png)

我的laravel是5.0的，由于当初使用的是laravel-pinyin的低版本，今天composer更新的时候，发现被自动更新到了高版本，导致出错。虽然我强行使用了低版本但是错误仍然存在，我猜测是不是图片中我框出来的那个对于overtrue/pinyin依赖的版本问题，因为本地的overtrue/pinyin是版本并不是与之匹配的低版本。

很感谢您的代码解决了我的拼音问题，帮忙看一下这个问题嘛，谢谢。

**Comment by overtrue** [comment]
从头到尾我都没发现你所谓的 “错误” 在哪儿。。。

**Comment by Tobess** [comment]
下面是错误提示：
PHP Fatal error:  Call to undefined method Overtrue\Pinyin\Pinyin::settings() in       ***/vendor/overtrue/laravel-pinyin/src/ServiceProvider.php on line 35

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method Overtrue\Pinyin\Pinyin::settings()

laravel-pinyin的版本为：1.2.1
昨天我主要想表达的是laravel-pinyin(1.2.1)所依赖的overtrue/pinyin的版本貌似不一致，我查看**/vendor/overtrue/pinyin/src/Pinyin.php的源码时里面并没有settings方法，而是高版本。

谢谢，也不知道我理解的对不对！

**Comment by overtrue** [comment]
我知道原因了，但是我还是建议你稍微改一下，改成 3.0 版本的用法，很快的

**Comment by Tobess** [comment]
项目当前正在大规模使用中，此时此刻主要想解决这个运行的事情，后期会修改成高版本的。您这里代码对于那个overtrue/pinyin的依赖会修正吗？
谢谢。

**Comment by overtrue** [comment]
如果你一定需要一个低版本的，我只好发布一个了，虽然这个修改成高版本基本就两行代码

**Comment by Tobess** [comment]
您帮我发布一个嘛，非常感谢！

**Comment by overtrue** [comment]
`composer require overtrue/laravel-pinyin:1.0.0-fix`

**Comment by Tobess** [comment]
好的，非常感激！
