### ISSUE TITLE
助手函数 pinyin()报错

### ISSUE THREAD

**Issue by xin6841414** [overtrue/laravel-pinyin#22]
pinyin()助手函数调用方法 function pinyin($string, $option = Pinyin::NONE){}， 这个Pinyin::NONE 没有这个常量，可用的option有PINYIN_DEFAULT，PINYIN_TONE，PINYIN_NO_TONE，PINYIN_ASCII_TONE，PINYIN_NAME等等， 没有NONE，overtrue/laravel-pinyin版本为4.0.0， overtrue/pinyin版本为4.0.5

**Comment by fasthold** [comment]
4.0.6 版本依然存在

**Comment by fasthold** [comment]
把 `Pinyin::NONE` 改成 `PINYIN_NO_TONE` 就好了
