### ISSUE TITLE
小写字符“k”无法成功转换

### ISSUE THREAD

**Issue by zqh375** [overtrue/laravel-pinyin#27]
![image](https://user-images.githubusercontent.com/52774045/94506810-d46ce180-0240-11eb-9c97-7793b7e70d5e.png)
![image](https://user-images.githubusercontent.com/52774045/94506825-dc2c8600-0240-11eb-931e-627a1d564fb1.png)

**Comment by overtrue** [comment]
https://github.com/overtrue/pinyin#%E5%8F%AF%E7%94%A8%E9%80%89%E9%A1%B9

**Comment by zqh375** [comment]
就k不行呀
