### ISSUE TITLE
设置大写无效

### ISSUE THREAD

**Issue by liuyami** [overtrue/laravel-pinyin#3]
我配置文件是使用小写的，间隔符号是："-"，我临时更改配置，间隔符号生效了，但是大写设置没有生效。

```
            Pinyin::settings([
                'delimiter' => ' ',
                'uppercase' => TRUE
            ]);

            echo Pinyin::trans('中国');exit;
```

上面代码，输出小写的：zhong guo

**Comment by overtrue** [comment]
![image](https://cloud.githubusercontent.com/assets/1472352/13383842/40227dbc-deca-11e5-91d2-40dfeeefff0f.png)
