### ISSUE TITLE
$this->loader 增加个配置项 可配置默认加载方式就更好啦

### ISSUE THREAD

**Issue by daixinguo** [overtrue/laravel-pinyin#31]
Overtrue\Pinyin\Pinyin

/**
   * Constructor.
   *
   * @param string $loaderName
   */
  public function __construct($loaderName = null)
  {
      // 这里的默认加载方式 增加一个配置文件 支持可配置就更完美啦
      $this->loader = $loaderName ?: 'Overtrue\\Pinyin\\FileDictLoader';
  }

**Comment by overtrue** [comment]
不用这么麻烦了，下一个版本没有这个 loader 选项了

**Comment by daixinguo** [comment]
会默认一个吗？还是引入新的技术实现
目前在 Overtrue\Pinyin\FileDictLoader 这个模式下 swoole-compiler代码加密后不支持
