### ISSUE TITLE
pinyin_abbr文档与源码显示return string 实际返回Collection

### ISSUE THREAD

**Issue by wnnnnnnn** [overtrue/laravel-pinyin#33]
dump(pinyin_abbr('带着希望去旅行'));

Overtrue\Pinyin\Collection {#1482 // app/Http/Controllers/Api/Admin/HerbController.php:17
  #items: array:7 [
    0 => "d"
    1 => "z"
    2 => "x"
    3 => "w"
    4 => "q"
    5 => "l"
    6 => "x"
  ]
}

if (!function_exists('pinyin_abbr')) {
    /**
     * Get the fist letters of given string.
     *
     * @param string $string
     * @param string $delimiter
     *
     * @return string
     */
    function pinyin_abbr($string, $delimiter = '')
    {
        return app(Pinyin::class)->abbr($string, $delimiter);
    }
} else {
    Log::warning('There exist multiple function "pinyin_abbr".');
}

**Comment by wnnnnnnn** [comment]
version 5.1

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-pinyin/commit/9e040fe96d38420e24d599ba5ed6314e1dab9512

**Comment by overtrue** [comment]
感谢反馈，已修复
