### ISSUE TITLE
Not working when using facade: Pinyin::permalink()

### ISSUE THREAD

**Issue by kxgio** [overtrue/laravel-pinyin#9]
And it works fine when I use: `Pinyin::permlink()`

**Comment by kxgio** [comment]
使用function模式时：`app('pinyin')->permalink()`
但若用 Facade，`Pinyin::permalink()` 会无效，需使用 `Pinyin::permlink()`
两者仅相差一个字母`a`，建议将 method 命名改为相同

**Comment by overtrue** [comment]
@kxgio 抱歉，未重现，我刚安装了一下测试一切正常。请提供以下版本信息：

``` shell
composer show overtrue/laravel-pinyin | grep versions
composer show overtrue/pinyin | grep versions
```

**Comment by kxgio** [comment]
versions : \* 3.0.2
versions : \* 3.0.0

**Comment by kxgio** [comment]
刚本地重新安装了一下测试也一切正常
线上的为3.0.0，应是3.0.0版本时的问题

**Comment by overtrue** [comment]
@kxgio OK，搞定就好
